export const INCREASE_PRODUCT = 'INCREASE_PRODUCT';
export const DECREASE_PRODUCT = 'DECREASE_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const CLEAR_CART = 'CLEAR_CART';
export const LOADING = 'LOADING';
export const DISPLAY_PRODUCTS = 'DISPLAY_PRODUCTS';
